# This workflow will check pull requests for not adding a changelog for
# thier pull requests and notify them to add one.
name: Changelog check

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Changelog checker
        uses: masterashu/check_changelog@v1.1
        with:
          changelog: "changelog/(\\d+)[.].*[.]rst"
          missing_changelog_message: >
            It seems like you forgot to add a changelog for your PR.

          skip_changelog_label: "No Changelog Required" 
          # Will skip the check if the Pull request has this label

          verify_pr_number: true
          # Make sure the changelog has the correct PR number
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"